apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: demo
spec:
  refreshInterval: 10s # Tần suất poll để đồng bộ nhanh chóng dưới 60s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: db-secret
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: demo/db/password
      metadataPolicy: None
